export { EditProfileModal } from './components/EditProfileModal'
export { ProfileHeader } from './components/ProfileHeader'
export { ProfileAbout } from './components/ProfileAbout'
export { ProfileActivity } from './components/ProfileActivity'
export { ProfileExperience } from './components/ProfileExperience'
export { ProfileEducation } from './components/ProfileEducation'
export { ProfileSkills } from './components/ProfileSkills'
export { ProfileContactInfo } from './components/ProfileContactInfo'
export { ProfileFeatured } from './components/ProfileFeatured'
export { ProfileAnalytics } from './components/ProfileAnalytics'
export { ProfileViewers } from './components/ProfileViewers'
export { ExperienceModal } from './components/ExperienceModal'
export { EducationModal } from './components/EducationModal'
export { FeaturedModal } from './components/FeaturedModal'
export { ResumeExportButton } from './components/ResumeExportButton'
// Legacy panels kept for backwards-compat — may be removed in a follow-up
export { ProfileTabs } from './components/ProfileTabs'
export type { ProfileTab } from './components/ProfileTabs'
export { AboutPanel } from './components/AboutPanel'
export { PostsPanel } from './components/PostsPanel'
export { BadgesPanel } from './components/BadgesPanel'
